@domain = https://localhost:4000/api

### 
# 회원가입
# 이 요청은 새 사용자를 등록합니다.
POST {{domain}}/signup
Content-Type: application/json

{
  "email": "pachyuchepe@gmail.com",
  "password": "123qweQWE!",
  "confirmPassword": "123qweQWE!",
  "name": "파츄체페",
  "role": "사장",
  "points": 100
}

### 
# 로그인
# 이 요청은 사용자 로그인을 처리합니다.
POST {{domain}}/login
Content-Type: application/json

{
  "email": "pachyuchepe@gmail.com",
  "password": "123qweQWE!"
}

### 
# 사용자 정보 조회
# 이 요청은 현재 로그인된 사용자의 정보를 조회합니다. (인증 토큰 필요)
GET {{domain}}/user
Content-Type: application/json

### 
# 사용자 정보 업데이트
# 이 요청은 사용자 정보를 업데이트합니다. (인증 토큰 필요)
PUT {{domain}}/user
Content-Type: application/json

{
  "currentPassword": "oldpassword",
  "newPassword": "newpassword",
  "name": "파츄체페 업데이트"
}

### 
# 사용자 삭제
# 이 요청은 현재 로그인된 사용자를 삭제합니다. (인증 토큰 필요)
DELETE {{domain}}/user
Content-Type: application/json

### 
# 로그아웃
# 이 요청은 사용자 로그아웃을 처리합니다.
POST {{domain}}/logout
Content-Type: application/json

### 
# 인증번호 요청
# 이 요청은 이메일 인증번호를 요청합니다.
POST {{domain}}/request-verify
Content-Type: application/json

{
  "email": "pachyuchepe@gmail.com"
}

### 
# 인증번호 확인
# 이 요청은 이메일 인증번호를 확인합니다.
POST {{domain}}/validate-verify
Content-Type: application/json

{
  "email": "pachyuchepe@gmail.com",
  "verifyCode": "123456"
}

# ==========================================================

### 
# 업장 등록
# 이 요청은 새 업장을 등록합니다.
POST {{domain}}/createstore
Content-Type: application/json

{
  "name": "새 업장 이름",
  "storedescription": "업장 설명",
  "foodtype": "음식 종류",
  "storeaddresses": "업장 주소",
  "businesslicense": "사업자 등록증 정보"
}

### 
# 업장 정보 수정
# 이 요청은 기존 업장의 정보를 수정합니다.
PUT {{domain}}/updatestore/1
Content-Type: application/json

{
  "name": "업데이트된 업장 이름",
  "storedescription": "업데이트된 업장 설명",
  "foodtype": "업데이트된 음식 종류",
  "storeaddresses": "업데이트된 업장 주소"
}

### 
# 업장 삭제
# 이 요청은 특정 업장을 삭제합니다.
DELETE {{domain}}/deletestore/1
Content-Type: application/json

### 
# 업장 전체 조회
# 이 요청은 등록된 모든 업장을 조회합니다.
GET {{domain}}/store

### 
# 업장 상세 조회
# 이 요청은 특정 업장의 상세 정보를 조회합니다.
GET {{domain}}/store/1